"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import toml
# from .custom_settings import cus_settings

project_root = os.path.abspath(os.path.dirname(__file__))

instance_name = ''
prop_config = toml.load(os.path.join(project_root, 'custom_settings/settings_config' + instance_name + '.toml'))

DEFAULT_DB_USER_NAME = prop_config.get('DATABASES').get('DEFAULT_DB_USER_NAME')
DEFAULT_DB_USER_PASSWORD = prop_config.get('DATABASES').get('DEFAULT_DB_USER_PASSWORD')
DEFAULT_DB_CONN_STRING = prop_config.get('DATABASES').get('DEFAULT_DB_CONN_STRING')
DEFAULT_SERVICES_URL = prop_config.get('DJANGO').get('DEFAULT_ENV_URL')

REDIS_HOST = prop_config.get('CACHING').get('REDIS_HOST')
REDIS_PORT = prop_config.get('CACHING').get('REDIS_PORT')
REDIS_AUTH = prop_config.get('CACHING').get('REDIS_AUTH')
REDIS_SERVICE_URL = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/1"

GCP_INTERIM_BUCKET = os.getenv('GCP_INTERIM_BUCKET')
LOG_FILE_PATH = os.getenv('LOG_FILE_PATH')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd3jnjqp#5avf#-w6@_3mo22b79vl&nx98bnqhnc3!!==8c)pwg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'django.contrib.redirects',
    'django.contrib.sites',
    'rest_framework',
    'sequences.apps.SequencesConfig',
    'drf_yasg',
    'cleardrop',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django_globals.middleware.Global',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'proj_main.middleware.ReqHandler.ReqPreProcessor',
    'proj_main.middleware.RespHandler.RespPostProcessor',
]

ROOT_URLCONF = 'proj_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        }
    },
]

WSGI_APPLICATION = 'proj_main.wsgi.application'

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.oracle',
    #     'NAME': DEFAULT_DB_CONN_STRING,
    #     'USER': DEFAULT_DB_USER_NAME,
    #     'PASSWORD': DEFAULT_DB_USER_PASSWORD,
    # }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_SERVICE_URL,
        "OPTIONS": {
            "PASSWORD": REDIS_AUTH,
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
    }
}

DATABASE_ROUTERS = ['proj_main.dbrouters.CDDBRouter']

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# LOGGING = VAR_LOGGING
# LOG_VIEWER_FILES_DIR = LOG_FILE_PATH
# LOG_VIEWER_MAX_READ_LINES = 1000  # total log lines will be read
# LOG_VIEWER_PAGE_LENGTH = 25       # total log lines per-page
# LOG_VIEWER_FILE_LIST_TITLE = "Custom Logging"

# Debug
INTERNAL_IPS = ['127.0.0.1']
